apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./flux-system/gotk-components.yaml
- ./flux-system/gotk-sync.yaml
- onboard-projects.yaml
- infra.yaml
patchesStrategicMerge:
- expose-webhook-receiver.yaml
